// <auto-generated>  This file is generated by CmsModelsGenerator. Do not edit manually. </auto-generated>
namespace Constants
{
    public static class Models
    {

        // --- Ungrouped ---
        public const string CMSEnity = "CMS/CMSEnity";
        public const string Day1Messages = "CMS/Chat/Day1Messages";
        public const string GiveEatTask = "CMS/Tasks/GiveEatTask";
        public const string Man1CharacterEntity = "CMS/Characters/Man1CharacterEntity";
        public const string Man2CharacterEntity = "CMS/Characters/Man2CharacterEntity";
        public const string MusicOnNight = "CMS/Tasks/MusicOnNight";
        public const string ReactionMessages = "CMS/Chat/ReactionMessages";
    }
}
